### ISSUE TITLE
Add Urdu(Pakistani)

### ISSUE THREAD

**Issue by RazaDaAli55** [openmultiplayer/homepage#102]

**Comment by markski1** [comment]
Feel free to open a Pull Request with the translated texts.

You can use the English (or any other language you prefer) file as a template from [here](https://github.com/openmultiplayer/homepage/tree/master/language) ; and push the translation into the same directory with the name Urdu.jsx

**Comment by Sasino97** [comment]
![image](https://user-images.githubusercontent.com/17410173/94972179-af919c00-04d6-11eb-9afe-af0d315498da.png)
Flag is missing for Urdu

**Comment by AliLogic** [comment]
PR #168 fixes it.

**Comment by Southclaws** [comment]
https://github.com/openmultiplayer/homepage/issues/179
