### ISSUE TITLE
Progress page has blank items

### ISSUE THREAD

**Issue by Southclaws** [openmultiplayer/homepage#104]
![image](https://user-images.githubusercontent.com/1636971/59330491-877e9800-8ce9-11e9-94b1-b213155f9ac1.png)

**Comment by NoEch0** [comment]
Not at least currently able to re-create this issue. Is it still visible to you or should it be closed?

**Comment by jtylr** [comment]
Unable to reproduce here too.

Happy to close @Southclaws?

**Comment by Southclaws** [comment]
I rewrote this page to fix this and a number of other issues and forgot to close this!
