### ISSUE TITLE
Progress page crashes on some mobiles when pushing language button

### ISSUE THREAD

**Issue by WoutProvost** [openmultiplayer/homepage#106]
^ best title

**Comment by jtylr** [comment]
>progress:1 Access to fetch at 'https://open.mp/api/progress' from origin 'https://www.open.mp' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

potentially this: https://github.com/openmultiplayer/homepage/blob/master/pages/progress.jsx#L18
