### ISSUE TITLE
wiki page doesn't redirect.

### ISSUE THREAD

**Issue by catalingrigoriev285** [openmultiplayer/homepage#165]
Hi, on page : **[missing-sites](https://www.open.mp/missing-sites)**, not working link : **wiki.open.mp**
html : `<a href="https://wiki.open.mp" class="jsx-3129667745 ">wiki.open.mp</a>` need to change to : 
`<a href="https://www.open.mp/docs/index" class="jsx-3129667745 ">wiki.open.mp</a>`

**Comment by Southclaws** [comment]
Ah yes, new URL, thanks!

**Comment by Sasino97** [comment]
Still not working for me; it's redirecting me to the home page

**Comment by Southclaws** [comment]
![image](https://user-images.githubusercontent.com/1636971/94973449-a9fe7b00-0503-11eb-8cc3-aa9f2f1dfa41.png)

cached
