### ISSUE TITLE
Fallback fonts for non-Latin alphabets

### ISSUE THREAD

**Issue by Southclaws** [openmultiplayer/homepage#62]
The English font is nice but the fallback is Arial which looks... not so nice.

We need some fallback fonts for Cyrillic etc.

**Comment by ghost** [comment]
Bonjour. I can say that a Segoe UI font (the UI font in Windows) looks pleasant to the eyes on Russian if also decrease a CSS line-height property from 1.8 to 1.5. (Google Translate)

**Comment by Southclaws** [comment]
Thank you for the recommendation, I will consider Sergoe UI as the primary fallback font for Cyrillic.

**Comment by ghost** [comment]
Also do you can auto select a language when someone enter the site? Just something like that
```javascript
const lang = (navigator.language || 'en-gb').toLowerCase();
// ...
```

**Comment by Southclaws** [comment]
Yes, but this belongs in another ticket.
