### ISSUE TITLE
Language icon overlaps the logo in mobile phone browser

### ISSUE THREAD

**Issue by jetttheshogun** [openmultiplayer/homepage#65]
The language changing icon overlaps the logo in portrait mode , it appears OK in landscape although i recommend cross checking.

For reference of what is happening here is the image:

![Screenshot_20190420-075843_Chrome](https://user-images.githubusercontent.com/38765096/56454224-1a92f580-636b-11e9-996f-bae7ee9dfbc2.jpg)

**Comment by Y-Less** [comment]
Fixed the title.
