### ISSUE TITLE
Progress page should show % on issues.

### ISSUE THREAD

**Issue by Y-Less** [openmultiplayer/homepage#79]
Even the open ones have progress from how we set them up.  Show that.

**Comment by Southclaws** [comment]
It seems this is all done client-side as I can't find anything related to task lists in the API. Not impossible though, I can naïvely search for `- [ ]` and `- [x]` and calculate it from that.

**Comment by Southclaws** [comment]
https://github.com/openmultiplayer/homepage/issues/179
